import { cases } from './cases.js';
const $=s=>document.querySelector(s);
let answers=[],busy=false,settings={leadEndpoint:'/api/lead',meeting_url:null};
fetch('clara-config.json').then(r=>r.json()).then(c=>{settings={leadEndpoint:c.leadEndpoint==='/api/lead'?c.leadEndpoint:'',meeting_url:null};}).catch(()=>{});
const questions=[
 ['Onde faria mais diferença começar?',cases.map(c=>[c.id,c.sector])],
 ['Por onde chegam hoje estes pedidos ou sinais?',[['email','Email'],['whatsapp','WhatsApp'],['system','Sistema / formulário'],['manual','Registo manual']]],
 ['Como está organizada a informação?',[['api','CRM / ERP com integrações'],['sheets','Folhas de cálculo'],['docs','Documentos dispersos'],['unknown','Ainda precisamos de mapear']]],
 ['Qual é a frequência aproximada?',[['low','Algumas vezes por semana'],['daily','Todos os dias'],['high','Muitas vezes por dia']]],
 ['Como prefere começar?',[['draft','Preparar para a equipa aprovar'],['bounded','Automatizar tarefas com regras claras'],['explore','Primeiro, compreender a viabilidade']]]
];
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function choice(id){return cases.find(c=>c.id===id)||cases[0];}
function message(text,role){const e=el('p',text,'chat-message '+role);$('#clara-history').append(e);}
function plan(){const c=choice(answers[0]);return {scenario:c.id,title:c.title,channel:answers[1],systems:answers[2],frequency:answers[3],approach:answers[4],trigger:c.trigger,agent:c.agent,action:c.action,review:c.review,metric:c.metric,needs:c.needs};}
function label(i){return questions[i][1].find(x=>x[0]===answers[i])?.[1]||'';}
function draw(){
 $('#clara-history').replaceChildren();message('Olá, sou a Clara. Vamos encontrar um primeiro processo com potencial. Não precisa de deixar contactos para explorar.','assistant');
 answers.forEach((a,i)=>{message(questions[i][0],'assistant');message(label(i),'user')});
 $('#clara-controls').replaceChildren();$('#clara-progress').value=answers.length;$('#clara-step').textContent=answers.length===5?'Diagnóstico concluído':`Passo ${answers.length+1} de 5`;
 if(answers.length<5){message(questions[answers.length][0],'assistant');const options=el('div',undefined,'clara-options');questions[answers.length][1].forEach(([id,text])=>{const b=el('button',text);b.type='button';b.onclick=()=>{answers.push(id);draw();$('#clara-controls button')?.focus({preventScroll:true})};options.append(b)});$('#clara-controls').append(options)}else{message('Já temos uma primeira hipótese. Veja o mapa ao lado. Pode guardar o resumo ou pedir uma análise técnica, sem compromisso.','assistant');showResult();}
 if(answers.length){const back=el('button','← Rever resposta anterior','clara-back');back.type='button';back.onclick=()=>{answers.pop();draw()};$('#clara-controls').append(back)}
 updateMap();$('#clara-history').scrollTop=$('#clara-history').scrollHeight;
}
function updateMap(){const c=choice(answers[0]);$('#flow-title').textContent=answers.length?c.title:'Da ideia ao fluxo.';$('#flow-description').textContent=answers.length?c.sector+' · proposta inicial':'Cada resposta aproxima o desenho da sua realidade.';$('.canvas-status').textContent=answers.length===5?'PROPOSTA INICIAL':'EM CONSTRUÇÃO';
 const nodes=[answers.length?'Contexto · '+c.sector:'O seu contexto',answers[1]?label(1)+' → '+c.trigger:'O que inicia o processo',answers[2]?c.agent+' · '+label(2):'Inteligência e contexto',answers[4]?c.review:'Controlo humano',answers.length===5?c.action:'Ação e acompanhamento'];$('#flow-nodes').replaceChildren(...nodes.map((text,i)=>el('li',String(i+1).padStart(2,'0')+' · '+text,answers.length>=([1,2,3,5,5][i])?'ready':'pending')));
 $('#flow-result').replaceChildren();if(answers.length===5){const heading=el('h4','Primeiro passo recomendado');const prereq=answers[2]==='api'?'Validar acessos e executar um piloto com dados de teste.':'Mapear e organizar as fontes de informação antes de ligar a automação.';$('#flow-result').append(heading,el('p',prereq),el('h4','Medir antes e depois'),el('p',c.metric),el('h4','O que precisamos de confirmar'),el('p',c.needs),el('p',answers[3]==='low'?'Com pouco volume, valide se o benefício compensa o esforço de integração.':'Priorize um processo repetitivo e acompanhe exceções, custo por execução e qualidade.'));}
}
function download(){const p=plan();const text=['ATLASHUB · DIAGNÓSTICO CLARA',p.title,...answers.map((_,i)=>questions[i][0]+' '+label(i)),'Fluxo: '+p.trigger+' → '+p.agent+' → '+p.action,'Controlo: '+p.review,'Pré-requisitos: '+p.needs,'Medir: '+p.metric,'Proposta exploratória. Não é orçamento nem confirmação de implementação.'].join('\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=el('a');a.href=url;a.download='AtlasHub-diagnostico.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function showResult(){const controls=$('#clara-controls');const save=el('button','Guardar o meu diagnóstico ↓','button primary');save.onclick=download;controls.append(save);const contact=el('button','Explorar o próximo passo →','button secondary');contact.onclick=showContact;controls.append(contact);}
function showContact(){const controls=$('#clara-controls');if($('#clara-contact'))return;const box=el('div',undefined,'clara-contact');box.id='clara-contact';box.append(el('h4','Como gostaria de continuar?'),el('p','Posso pedir confirmação de contacto, de uma reunião ou de uma análise para orçamento. O diagnóstico continua disponível sem partilhar dados.'));

 if(!settings.leadEndpoint){box.append(el('p','O contacto direto está em preparação. Por agora, guarde o diagnóstico para o partilhar com a equipa.'));controls.append(box);return;}
 const requestId=crypto.randomUUID();const form=el('form');form.innerHTML='<label>Como podemos tratar-lhe?<input name="name" autocomplete="name" maxlength="100" required></label><label>Empresa (opcional)<input name="company" autocomplete="organization" maxlength="160"></label><label>Email (ou WhatsApp abaixo)<input name="email" type="email" autocomplete="email" maxlength="160"></label><label>WhatsApp com indicativo (opcional se indicar email)<input name="phone" type="tel" autocomplete="tel" maxlength="30" placeholder="+351 …"></label><label>O próximo passo<select name="intent"><option value="contact">Gostaria de ser contactado</option><option value="meeting">Pedir uma reunião técnica</option><option value="quote">Análise para orçamento</option></select></label><label>Janela preferida para contacto ou reunião<input name="preferredWindow" maxlength="160" placeholder="Ex.: terça de manhã, hora de Lisboa"></label><label class="consent"><input name="consent" type="checkbox" required> Autorizo a AtlasHub a usar estes dados para responder a este pedido.</label><p class="privacy-note">Enviamos apenas os contactos e as escolhas deste diagnóstico à equipa AtlasHub. Não subscreve marketing. Uma reunião só fica marcada após confirmação.</p><label class="honeypot" aria-hidden="true">Website<input name="website" tabindex="-1" autocomplete="off"></label><button type="submit" class="button primary">Enviar pedido →</button><p class="form-status" role="status"></p>';
 form.onsubmit=async event=>{event.preventDefault();if(busy)return;const data=Object.fromEntries(new FormData(form));const status=form.querySelector('.form-status');if(data.intent==='meeting'&&!data.preferredWindow.trim()){status.textContent='Indique uma janela preferida para podermos pedir confirmação.';return}if(!data.email&&!data.phone){status.textContent='Indique email ou WhatsApp para podermos responder.';return}busy=true;const button=form.querySelector('button');button.disabled=true;status.textContent='A enviar o pedido…';try{const response=await fetch(settings.leadEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,requestId,consent:data.consent==='on',diagnostic:plan()}),signal:AbortSignal.timeout(12000)});const result=await response.json();if(response.status!==202||typeof result.id!=='string'||!result.id||result.route!=='human')throw Error();status.textContent='Pedido recebido para análise. Posso pedir confirmação por WhatsApp/email; a reunião ainda não está marcada.';form.reset();button.hidden=true;}catch{status.textContent='Não foi possível confirmar a receção. Guarde o diagnóstico e tente mais tarde.';}finally{busy=false;button.disabled=false}};box.append(form);controls.append(box);form.querySelector('input').focus({preventScroll:true});}
$('#clara-reset').onclick=()=>{if(busy)return;answers=[];draw()};document.querySelectorAll('[data-case]').forEach(button=>button.onclick=()=>{if(busy)return;answers=[button.dataset.case];draw();$('#clara').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});$('#clara-controls button')?.focus({preventScroll:true})});draw();
