import test from 'node:test';
import assert from 'node:assert/strict';
import handler,{validateLead} from '../api/lead.js';
const base=()=>({requestId:'11111111-1111-4111-8111-111111111111',name:'Teste',email:'test@example.com',consent:true,intent:'contact',diagnostic:{scenario:'sales',channel:'email',systems:'api',frequency:'daily',approach:'draft'}});
test('requires a contact and explicit consent',()=>{assert.throws(()=>validateLead({...base(),email:''}));assert.throws(()=>validateLead({...base(),consent:false}));assert.equal(validateLead({...base(),email:'',phone:'+351 900000000'}).phone,'+351 900000000')});
test('rejects invalid or excessive input and fabricated scenarios',()=>{for(const change of [{name:'a'.repeat(101)},{email:'invalid'},{phone:'123'},{website:'spam'},{diagnostic:{scenario:'fake'}}])assert.throws(()=>validateLead({...base(),...change}));assert.equal(validateLead({...base(),secret:'discard'}).secret,undefined)});
const call=async req=>{const result={headers:{}};const res={setHeader(k,v){result.headers[k]=v},status(s){result.status=s;return this},json(b){result.body=b;return this}};await handler(req,res);return result};
const req=()=>({method:'POST',headers:{origin:'https://atlashub.si','content-type':'application/json'},body:base()});
test('rejects cross-origin requests; fails closed when unconfigured',async()=>{delete process.env.LEAD_WEBHOOK_URL;assert.equal((await call({...req(),headers:{origin:'https://other.test'}})).status,403);assert.equal((await call(req())).status,503)});
test('only acknowledges downstream acceptance, with no live messages',async()=>{process.env.LEAD_WEBHOOK_URL='https://example.invalid/webhook';process.env.LEAD_WEBHOOK_TOKEN='test-only';const original=global.fetch;try{global.fetch=async()=>({status:200,json:async()=>({})});assert.equal((await call(req())).status,502);global.fetch=async()=>({status:202,json:async()=>({id:'lead-test',route:'human'})});assert.deepEqual((await call(req())).body,{id:'lead-test',route:'human'});global.fetch=async()=>{throw Error('timeout')};assert.equal((await call(req())).status,502)}finally{global.fetch=original;delete process.env.LEAD_WEBHOOK_URL;delete process.env.LEAD_WEBHOOK_TOKEN}});

test('meeting needs a preferred window and remains human',()=>{assert.throws(()=>validateLead({...base(),intent:'meeting'}));assert.equal(validateLead({...base(),intent:'meeting',preferredWindow:'Terça, 10h Lisboa'}).route,'human')});
