export const cases = [
  {
    id: "sales",
    sector: "Comercial",
    title: "Do primeiro contacto à oportunidade",
    trigger: "Pedido no site, email ou WhatsApp",
    agent:
      "Identificar intenção, resumir a necessidade e sugerir o próximo passo",
    action: "Criar oportunidade no CRM e preparar resposta",
    review: "A equipa aprova propostas e compromissos comerciais",
    metric: "Tempo de primeira resposta e oportunidades qualificadas",
    needs: "CRM com API, catálogo de serviços e regras de encaminhamento",
  },
  {
    id: "support",
    sector: "Atendimento",
    title: "Respostas com contexto, exceções com pessoas",
    trigger: "Nova questão de um cliente",
    agent:
      "Pesquisar documentação autorizada e preparar uma resposta com fontes",
    action: "Abrir ou atualizar ticket e encaminhar para a equipa certa",
    review:
      "Dúvidas sem fonte, reclamações e dados sensíveis seguem para uma pessoa",
    metric: "Resolução no primeiro contacto e taxa de encaminhamento",
    needs: "Base de conhecimento atualizada, permissões e helpdesk",
  },
  {
    id: "retail",
    sector: "Retail & Pharmacy",
    title: "Antecipar ruturas e preparar reposição",
    trigger: "Atualização de stock ou revisão diária",
    agent: "Explicar anomalias e reunir contexto de vendas e fornecedores",
    action: "Gerar alerta e rascunho de reposição",
    review:
      "Compras e alterações de preço exigem aprovação; sem aconselhamento clínico",
    metric: "Ruturas, tempo de análise e precisão dos alertas",
    needs: "ERP/POS acessível, dados de stock e regras de reposição",
  },
  {
    id: "industry",
    sector: "Industry & Supply Chain",
    title: "Transformar atrasos em ações coordenadas",
    trigger: "Email de fornecedor ou alteração de entrega",
    agent: "Extrair datas, identificar encomendas e resumir impacto",
    action: "Atualizar ocorrência e avisar responsáveis",
    review: "A equipa valida datas incertas e mudanças de planeamento",
    metric: "Tempo de deteção e resolução de exceções",
    needs: "Encomendas com identificadores, ERP e canal de notificações",
  },
  {
    id: "realestate",
    sector: "Real Estate",
    title: "Qualificar procura e preparar visitas",
    trigger: "Pedido sobre um imóvel",
    agent: "Relacionar preferências declaradas com imóveis disponíveis",
    action: "Registar lead e propor horários disponíveis",
    review:
      "Visita só é confirmada após disponibilidade e aceitação; sem decisões de crédito",
    metric: "Tempo de resposta e visitas confirmadas",
    needs: "Catálogo atualizado, CRM e agenda com API",
  },
  {
    id: "healthcare",
    sector: "Services & Healthcare",
    title: "Recuperar tempo na gestão de agendas",
    trigger: "Pedido de marcação ou cancelamento",
    agent: "Interpretar intenção administrativa e preparar encaminhamento",
    action: "Propor horários e enviar lembretes autorizados",
    review: "Sem diagnóstico clínico; alterações dependem das regras da agenda",
    metric: "Tempo administrativo e comparências",
    needs: "Agenda integrada, consentimentos e separação de dados clínicos",
  },
  {
    id: "documents",
    sector: "Backoffice",
    title: "Documentos que chegam prontos a validar",
    trigger: "Receção de uma fatura ou formulário",
    agent: "Extrair campos e sinalizar divergências",
    action: "Comparar com registos e preparar lançamento",
    review:
      "Valores, duplicados e pagamentos são validados por pessoas e regras",
    metric: "Tempo por documento e taxa de correções",
    needs: "Documentos legíveis, esquema de dados e regras contabilísticas",
  },
  {
    id: "operations",
    sector: "Operações",
    title: "Passar de relatórios a decisões informadas",
    trigger: "Fecho diário ou indicador fora do intervalo",
    agent: "Resumir desvios com referência aos dados de origem",
    action: "Criar tarefa e relatório para responsáveis",
    review: "Causalidade e decisões operacionais exigem validação",
    metric: "Tempo de preparação e tempo até à ação",
    needs: "Fontes reconciliadas, KPIs definidos e responsáveis",
  },
];
